name: Graphs CI
on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types:
      - graphs
      - graphs_*
  workflow_dispatch:

jobs:
  release:
    name: Generate graphs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate graphs
        uses: upptime/uptime-monitor@v1
        with:
          command: "graphs"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
